# Generated by Django 6.0.7 on 2026-07-15 01:19

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Image principale')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Lien vidéo (YouTube/Facebook...)')),
                ('playstore_url', models.URLField(blank=True, null=True, verbose_name='Lien Play Store')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Priorité (plus grand = plus visible)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='services/', verbose_name="Image d'illustration")),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Priorité (plus grand = plus visible)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Mon Agence', max_length=100, verbose_name="Nom de l'agence")),
                ('hero_title', models.CharField(default='Bienvenue sur notre site', max_length=200, verbose_name='Titre de la bannière')),
                ('hero_subtitle', models.TextField(default='Nous vous accompagnons dans votre transformation digitale', verbose_name='Sous-titre de la bannière')),
                ('hero_cta_text', models.CharField(default='Découvrir nos services', max_length=50, verbose_name='Texte du bouton CTA')),
                ('hero_cta_url', models.CharField(default='#services', max_length=200, verbose_name='Lien du bouton CTA')),
                ('about_text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Texte 'À propos'")),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Lien Facebook')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='Lien LinkedIn')),
                ('footer_copyright', models.CharField(default='© 2026 - Tous droits réservés', max_length=200, verbose_name='Copyright dans le footer')),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié sur le site')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visits', models.PositiveIntegerField(default=0, verbose_name='Nombre total de visites')),
            ],
            options={
                'verbose_name': 'Compteur de visiteurs',
                'verbose_name_plural': 'Compteur de visiteurs',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Photo')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Légende')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.product')),
            ],
            options={
                'verbose_name': 'Photo du produit',
                'verbose_name_plural': 'Photos des produits',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la réalisation')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('image', models.ImageField(upload_to='achievements/', verbose_name='Image du projet')),
                ('project_url', models.URLField(blank=True, null=True, verbose_name='Lien vers le projet')),
                ('description', models.TextField(blank=True, verbose_name='Description courte')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='core.service')),
            ],
            options={
                'verbose_name': 'Réalisation',
                'verbose_name_plural': 'Réalisations',
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/', verbose_name='Photo')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Légende')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.service')),
            ],
            options={
                'verbose_name': 'Photo du service',
                'verbose_name_plural': 'Photos des services',
                'ordering': ['order'],
            },
        ),
    ]
