# Generated by Django 6.0.7 on 2026-07-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorcounter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
