# Generated by Django 6.0.7 on 2026-07-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_visitorcounter_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='primary_color',
            field=models.CharField(default='#0d6efd', help_text='Couleur utilisée pour les boutons, liens, et arrière-plans', max_length=7, verbose_name='Couleur principale (ex: #0d6efd)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='secondary_color',
            field=models.CharField(default='#0a58ca', help_text='Couleur utilisée pour les survols et dégradés', max_length=7, verbose_name='Couleur secondaire (ex: #0a58ca)'),
        ),
    ]
