# Generated by Django 6.0.7 on 2026-07-15 14:18

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteconfig_primary_color_siteconfig_secondary_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#0d6efd', image_field=None, max_length=25, samples=None, verbose_name='Couleur principale (boutons, bannières)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='secondary_color',
            field=colorfield.fields.ColorField(default='#0a58ca', image_field=None, max_length=25, samples=None, verbose_name='Couleur secondaire (dégradés, survols)'),
        ),
    ]
