# Generated by Django 6.0.7 on 2026-07-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_siteconfig_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Lien Instagram'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='telegram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Lien Telegram'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True, verbose_name='Lien TikTok'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='whatsapp_message',
            field=models.CharField(blank=True, help_text="Message qui s'affichera à l'ouverture de la conversation WhatsApp", max_length=200, null=True, verbose_name='Message pré-défini (optionnel)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro WhatsApp (ex: 237691xxxxxx)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='Lien YouTube'),
        ),
    ]
