# Generated by Django 6.0.7 on 2026-07-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_siteconfig_instagram_url_siteconfig_telegram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='theme_choice',
            field=models.CharField(choices=[('classic', 'Classique (sobre et professionnel)'), ('modern', 'Moderne (couleurs vives, ombres)'), ('elegant', 'Élégant (polices fines, tons pastel)')], default='classic', max_length=20, verbose_name='Thème du site'),
        ),
    ]
