# Generated by Django 6.0.7 on 2026-07-22 13:08

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_siteconfig_theme_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='background_color',
            field=colorfield.fields.ColorField(blank=True, default='#ffffff', help_text="Laisser vide pour utiliser l'image de fond", image_field=None, max_length=25, null=True, samples=None, verbose_name='Couleur de fond du site'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Sera utilisée si la couleur de fond est vide', null=True, upload_to='backgrounds/', verbose_name='Image de fond du site'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='background_position',
            field=models.CharField(choices=[('center center', 'Centré'), ('top center', 'En haut centré'), ('bottom center', 'En bas centré'), ('left center', 'Gauche centré'), ('right center', 'Droite centré'), ('top left', 'Haut gauche'), ('top right', 'Haut droite'), ('bottom left', 'Bas gauche'), ('bottom right', 'Bas droite')], default='center center', max_length=30, verbose_name="Position de l'image de fond"),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='background_repeat',
            field=models.CharField(choices=[('no-repeat', 'No-repeat'), ('repeat', 'Repeat'), ('repeat-x', 'Répéter horizontalement'), ('repeat-y', 'Répéter verticalement')], default='no-repeat', max_length=20, verbose_name="Répétition de l'image"),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='background_size',
            field=models.CharField(choices=[('cover', 'Couvrir (Cover)'), ('contain', 'Contenir (Contain)'), ('auto', 'Auto')], default='cover', max_length=20, verbose_name="Taille de l'image de fond"),
        ),
    ]
