# Generated by Django 6.0.7 on 2026-07-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_siteconfig_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='domain',
            field=models.CharField(blank=True, help_text='Utilisé pour générer le sitemap et les liens absolus', max_length=100, null=True, verbose_name='Domaine du site (ex: vitrinecis.groupesiewe.com)'),
        ),
    ]
